Add GDF2 class tests
kinverarity1/aseg_gdf2 pull request #23
Opened 2020-10-11 18:13 UTC by dcslagel

#### Description 

This pull request adds a 2 GDF2 specific tests  to improve test coverage

- Add separate test file for GDF2 specific tests
- Add test for GDF2's repr which will include the number of records
- Add test for GDF2.get_column_definitions()

#### Tests

All tests pass

pytest results before this pull-request:
```
Name                    Stmts   Miss  Cover
-------------------------------------------
aseg_gdf2/__init__.py       2      0   100%
aseg_gdf2/gdf2.py         270     54    80%
-------------------------------------------
TOTAL                     272     54    80%
```

pytest results after this pull-request:

```
Name                    Stmts   Miss  Cover
-------------------------------------------
aseg_gdf2/__init__.py       2      0   100%
aseg_gdf2/gdf2.py         270     38    86%
-------------------------------------------
TOTAL                     272     38    86%
```

Let me know if this change could be accepted (or rejected) or
needs some additional changes before being approved and merged.

Thank you,
DC

2020-10-12 01:53 UTC, kinverarity1 reviewed
Hey @dcslagel  - thanks so much for looking at the test coverage!

One suggestion here though here - `0x10cfdead0` will change every time right, isn't it the memory location? We should match it in the text with a regex or just do a different test to avoid it.

2020-10-12 02:34 UTC, dcslagel commented
@kinverarity1, 

Good catch.  :-)  

It is weird and interesting, the test keeps passing but the memory location should have changed.  
Yep, I'll dig into it,  make the fix and post it in the next few days.

DC

2020-10-12 14:05 UTC, dcslagel commented
@kinverarity1 , 

Commit 4af393d fixes the broken assert tests:
- It corrects the assert syntax in the test_gdf_class tests. (The incorrect syntax was causing the tests to always pass).
- Changes the test_repr_1() test to check only that the test ends with the correct number of records.

In addition, this change changes GDF2's __repr__() method to use self.nrecords rather than self._nrecords.  This is because self.nrecords() need to run at least once to report the correct number of nrecords.   

The Codacy/PR Quality Review is reporting the asserts as bad because they will be removed when the python code is compiled to object code, but this shouldn't be a problem for the test code and asserts are used in the other parts of the asset_gdf2 test suite.  If you agree, then it would be good to see if Codacy can ignore the tests directory for the assert check.  

Let me know if this pull-request need further improvement to be accepted.

Thanks!,
DC

2020-10-26 06:06 UTC, kinverarity1 requested changes
Thanks @dcslagel see comments.

2020-10-26 06:06 UTC, kinverarity1 commented on aseg_gdf2/gdf2.py
> +        nrecords = self.nrecords
Can we revert this? `self.nrecords` takes a long time for very large files, which is why it is behind a property method. It shouldn't be calculated until the user explicitly requests it or a method needs it.

2020-10-26 06:06 UTC, kinverarity1 commented on tests/test_gdf2_class.py
> +    res = gdf.__repr__()
If you revert the change to `GDF2.__repr__`, then all we need here is to insert something like `blahblah = gdf.nrecords`, which will trigger the calculation of the number of rows.

In fact you could probably test the entire behaviour here: initially `repr(gdf)` should report nrecords=? and only after the access of the property would it report the number of rows as the current test checks.

2020-10-26 14:10 UTC, dcslagel commented on aseg_gdf2/gdf2.py
> +        nrecords = self.nrecords
This change is made in commit a1c6d0b.  I also added some notes to make the gdf.nrecords delayed resolution purpose more explicit.  Let me know if the notes need to be improved or removed.

2020-10-26 14:13 UTC, dcslagel commented on tests/test_gdf2_class.py
> +    res = gdf.__repr__()
This change is made in commit a1c6d0.  The steps and asserts in test_repr_1() are arranged as you suggested so that the whole behavior is demonstrated.  Let me know if it needs additional improvement.

2020-12-21 01:26 UTC, dcslagel commented
Hi @kinverarity1 ,

I'm just following up on old pull-requests.  I think that I've made all the changes requested.  Let me know if there are further concerns to be addressed.  (It looks like the Codacy/PR Quality Review failed but it is not displaying the error for me.  Let me know if there is something I can fix there.)

Thank you,
DC

2021-01-21 10:13 UTC, kinverarity1 approved these changes
Thank you! So sorry that it has taken me so long to get to this!

2021-01-21 10:13 UTC, merged